### ISSUE TITLE
Sending tx with all funds (around 4000-10000 sats) throws dust error

### ISSUE THREAD

**Issue by felipebrunet** [lnbits/hardware-wallet#20]
I had an issue with the Hardware Wallet (TTGO ESP32) Using the Onchain wallet extension.
I sent some txs with no issues until the last one. 
I had about 4100 sats left, I tried to send them all to another address, paying 6 sats/vb as fee and no return change.
When I created the transaction on the Onchain Wallet extension, after broadcasting it the system threw a 400 popup error.
Then I tried to broadcast it by other websites, and they threw the dust error.

So I tried to send the same tx using electrum (re creating the wallet by entering the seed associated to the hardware wallet). When I broadcasted it the transaction went through with no problem.
So I figured out the problem was about the encoding of the transaction.

LNBits encoded this:
0200000000010161d06d947042b83859aa8e3000c08badf0d705d3994ff0af09cdc79797cc134c0100000000ffffffff02ec0c0000000000001600147d31df416c49df931de70b3d72a61d4d34809e6800000000000000001600141644411c3ab5228c073b032f13546c12cb9d72c502483045022100add32badafc7a2995eaaf526daf4251c91da137db71c6de28bcb6e1616e6dbda022030bc554b7d064bf44f3d3500327cd0d87af44e13de9b1866f5cc9ea741757b070121031a068b6f8ee0897719bd44670a2cdaa2f45b375490a5d7868edb1fbadb5689b900000000

Electrum encoded the following:
0200000000010161d06d947042b83859aa8e3000c08badf0d705d3994ff0af09cdc79797cc134c0100000000fdffffff01a60d0000000000001600147d31df416c49df931de70b3d72a61d4d34809e68024730440220562b6207f2f3a40a403231a1aa262be879b009b73ba263ad3ac6ef62a597d24a02201433e9e8f100a5fc5ac36e9564097c381a5aee48b7054ea877e99f4206bfed5d0121031a068b6f8ee0897719bd44670a2cdaa2f45b375490a5d7868edb1fbadb5689b9d2dc0b00

If you decode both, you will see everything is the same except for the "received" and "relayed_by" fields. 
But that should not have caused the error. 

If you try to push both transactions on [https://blockstream.info/tx/push], you will see that both fail of course (because the one I broadcasted from electrum is already mined), but the messages are completely different.

When you enter the encoded tx from LNbits, the website still displays the dust error:
"sendrawtransaction RPC error: {"code":-26,"message":"dust"}"

When you enter the one from electrum you get: 
"sendrawtransaction RPC error: {"code":-27,"message":"Transaction already in block chain"}"

Why is this? is it possible that the Onchain wallet extension is encoding the transaction the wrong way?
Sorry my ignorance if I missed something. 

The Electrum transaction that was mined is this one
6097c8e9155005b7a73fa3448774ac31be454d2b4dc8671a87907ec75d6e1a23

Thanks!

**Comment by motorina0** [comment]
Sorry for the very late reply. My notifications were off for this repo.

- I had a look at the TX (using [this tool](https://bitcoincore.tech/apps/bitcoinjs-ui/index.html)) and it has an output with `amount` zero.
   - ![image](https://github.com/lnbits/hardware-wallet/assets/2951406/3139af3c-d3c3-47e0-ad3c-75afea1c2467)

- in the latest version there is an UI check for amounts lower than the dust limit (maybe that was not the case when you have built that psbt)

**Comment by felipebrunet** [comment]
Thanks! I will try it again since I updated my lnbits version as well.
I believe the problem is about the encoding generated by the LNBits extension. That "0 sats" utxo makes sense, since I was sending all funds to the other address. What the extension should have done is to simply not include that utxo in the transaction, just like Electrum did.
