### ISSUE TITLE
Isolating private data from coordinator

### ISSUE THREAD

**Issue by odudex** [lnbits/hardware-wallet#24]
I did not try the project myself, but I noticed in the code methods to send the mnemonic to the coordinator device.
I think it would be a good idea to change the workflow and remove these methods to avoid leaking any of wallet's private data to the coordinator, the PC/browser. Leaking the mnemonic to the device defeats one of the purposes of hardware wallets, which is to keep private data out of reach of the coordinator.

**Comment by motorina0** [comment]
The communication between the browser and the hardware device is encrypted.

How would you restore the mnemonic on the device if there are not methods to do so?
